config/routes.rb
Rails.application.routes.draw do

  resources :conferences do
    collection do
      get :notifications
      post :delegate
    end
  end

  resources :messages

  match "/manifest" => "dashboard#cache_manifest"
  
  resources :authors do
    member do
      post :replace
    end
  end

  resources :submissions do
    member do
      put :update_institutions
    end
  end
  
  resources :umin_rows

  resources :meet_up_comments

  resources :participations

  resources :meet_ups do
    member do
      put 'participate'
    end
  end

  resources :global_messages
  
  resources :receipts do
    collection do
      put 'mark_read_by_sender'
      put 'mark_read'
      put 'mark_unread'
    end
  end

  resources :likes do
    collection do 
      get 'by_day'
      post 'batch_request_likes'
      post 'vote'
      get 'my_votes'
      get 'likes_report'
      get 'votes_report'
    end
    member do
      get 'my'
      get 'my_schedule'
      put 'schedulize'
      put 'unschedulize'
      put 'secretify'
    end
  end

  get "user_sessions/new"

  get "browser(/:session_id)" => "browser#list", :as => :list_browser

  get "browser/details/:presentation_id" => "browser#details"
  
  get "login" => "user_sessions#new", :as => :login
  get "logout" => "user_sessions#destroy", :as => :logout

  get "schedule" => "schedule#index"

  resources :pages

  resources :authorships do
    collection do
      post 'sort'
      post 'drop_on_submission'
    end
  end

  resources :comments do
    member do
      get 'reply'
    end
  end

  resources :rooms do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  
  resources :poster_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end
    collection do
      get 'container'
    end
  end

  resources :booth_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end    
  end
  
  resources :timetable do
    member do
      get 'like_highlights'
      get 'list'
    end
    collection do
      get 'container'
    end
  end
  
  resources :dashboard do
    collection do
      get 'liked_presentations_ajax'
      get 'my_presentations_ajax'
      get 'scheduled_presentations_ajax'
      get 'private_messages_ajax'
      get 'meet_ups_ajax'
      get 'global_messages_ajax'
      get 'notifications'
      get 'global_messages'
      get 'my_presentations'
      get 'my_meet_ups'
      get 'private_messages'
      get 'social_links'
      post 'batch_request_pages'
    end
  end
  
  resources :sessions do
    member do
      get 'detail'
      get 'poster_row'
      get 'social_box'
      get 'poster_social_box'
      get 'download_pdf'
      get 'download_full_day_pdf'
      put 'order_presentations_by_number'
      put 'set_presentation_duration'
      get 'query'
      put 'change_children_presentation_types'
    end
    collection do
      post 'batch_request_liked_sessions'
      get 'download_full_pdf'
      get 'download_pdf_by_name'
    end
  end

  resources :presentations do
    member do
      get 'next'
      get 'previous'
      get 'likes'
      get 'comments'
      get 'social_box'
      put 'toggle_schedule'
      post 'create_comment'
      get 'related'
      get 'heading'
      put 'change_ad_category'
    end
    collection do
      get 'my'
      post 'sort'
      post 'batch_request_likes'
    end
  end

  resources :users do
    member do
      put 'set_global_message_to_read'
      put 'reset_read_global_messages'
      get 'settings', :to => 'users#settings'
      put 'settings', :to => 'users#update_settings'
      get 'edit_name'
      put 'update_name'
      get 'admin_panel'
      put 'assign_author'
    end
    collection do
      get 'admin_search'
      get 'admin_search_by_registration_id'
    end
  end
  
  resources :user_sessions do
    collection do
      post 'switch'
    end
  end
  
  resources :private_messages do
    collection do
      get 'threads'
    end
  end

  match 'private_messages/conversation/:with' => 'private_messages#conversation', :as => 'conversation_private_messages'

  resources :search

  match 'docs/batch' => 'docs#batch', :as => "docs_batch"
  match 'docs/test_batch' => 'docs#test_batch', :as => "docs_test_batch"
  match 'docs(/:folder)/manifest' => 'docs#manifest', :as => "docs_manifest"
  match 'docs/:page(/:sub_page)' => 'docs#show', :as => "docs", :via => [:get]
  match 'docs/:page(/:sub_page)' => 'docs#create', :as => "docs", :via => [:post]
  match 'docs(/)' => 'docs#index', :as => "docs_root"

  match 'tests/:page(/:sub_page)' => 'tests#show', :as => "tests", :via => [:get]

  match 'admin/:action' => 'admin', :as => "admin"

  match ':page' => 'static#show', :as => :static, 
        :constraints => {:page => /ponzu_frame|ponzu_admin_frame|rake_reports/}

  match 'system/ks_cache_version' => "conferences#ks_cache_version", :as => :ks_cache_version

  root :to => 'static#layout'

end

app/models/authorship.rb
# encoding: UTF-8

# This is a join table connecting presentations to 
# their authors.
#
# Unlike previous version (before NGS2015), Authorships were created only 
# by the batch system and administrators.
#
# Since NGS2015, we introduced a Registration inteface for normal users
# which means we need to do a lot of validations.
class Authorship < ActiveRecord::Base
  attr_accessible :presentation_id, :user_id, :switch_user, :jp_name, :en_name,
                  :submission_id, :author_id, 
                  :position, :affiliations, :is_presenting_author, :affiliations_yaml,
                  :_sync_author_names
  attr_accessor :skip_affiliations_validation

  # `_sync_author_names` triggers the `sync_author_if_requested_and_only_authorship_on_author` method
  # which makes sure that the Author name and Authorship are in sync (but only if there is only one Authorship)
  # for that Author.
  attr_accessor :_sync_author_names
  belongs_to :submission, :inverse_of => :authorships, :touch => true
  belongs_to :author, :inverse_of => :authorships, :touch => true
  after_destroy :destroy_author_if_orphan
  
  acts_as_list :scope => :submission

  include BatchImportMixin

  validates_presence_of :submission_id
  validate :name_is_set
  validates_presence_of :affiliations_string, 
                        :unless => Proc.new{|authorship| 
                                              authorship.skip_affiliations_validation == true ||
                                              authorship.author && (authorship.author.batch_import == true) ||
                                              authorship.submission && (authorship.submission.batch_import == true)
                                            }

  # The email address is currently a dummy and we don't do anything with it.
  # It was introduced for NGS2015.
  validates_presence_of :email, if: :require_email_in_authorships
  validates_format_of :email, :with => Authlogic::Regex.email, if: :require_email_in_authorships

  validate :affiliation_institutes_are_set
  validate :en_name_format
  validate :jp_name_format

  before_validation :fill_conference_tag_if_nil
  before_validation :fill_names_if_nil
  before_validation :uniquify_affiliations

  before_save :create_author_if_absent

  after_save :sync_author_if_requested_and_only_authorship_on_author

  locale_selective_reader :name, :en => :en_name, :ja => :jp_name

  validates_uniqueness_of :submission_id, :scope => :author_id

  # validate :submission_and_author_conferences_must_match

  include SimpleSerializer
  serialize_array :affiliations, :typecaster => :convert_affiliations_to_integers,
                  :sort => Proc.new {|a, b| a <=> b}

  include ConferenceRefer
  validates_conference_identity :author, :submission
  infer_conference_from :submission

  # :section: To calculate related Submissions

  # Returns an AuthorAppearances object
  # which holds information on how many times each
  # author appeared in the list of authorships.
  #
  # Deprecated because is shouldn't be Authorship centric.
  # Rather, it should be a method of Author.
  #
  # See Author#frequency_in,
  def self.author_frequency_in_authorships(authorships)
    raise "call on deprecated Authorship#author_frequency_in_authorships"
    Author.frequency_in(authorships.map{|au| au.submission})
  end

  def looking_for_job?
    author.looking_for_job?
  end

  def looking_for_person?
    author.looking_for_person?
  end

  def looking_for_partner?
    author.looking_for_partner?
  end

  def affiliations_string
    affiliations.join(",")
  end

  def affiliations_string= (string)
    self.affiliations = string.split(/,/).map{|n| n.strip}
  end

  private

  # params[authorships][affiliations][] will return an
  # array of strings, but we need to convert them into integers.
  #
  # Furthermore, this removes any blank strings which are used
  # in a hidden field to circumvent the "value not sent if none-checked" issue.
  def convert_affiliations_to_integers(affiliations)
    affiliations.map{|aff| aff.to_i if !aff.blank?}.compact
  end

  # def submission_and_author_conferences_must_match
  #   if conference != author.conference || conference != submission.conference
  #     errors.add(:base, "Conference for Authorship, Submission and Author must match.")
  #   end
  # end

  def fill_names_if_nil
    if en_name.blank? && jp_name.blank?
      self.en_name = author.en_name
      self.jp_name = author.jp_name
    end
  end

  def fill_conference_tag_if_nil
    if conference_tag.nil?
      if ct = submission.conference_tag || author.conference_tag
        self.conference_tag = ct
      end
    end
  end

  def create_author_if_absent
    if author_id.nil?
      a = Author.new(:en_name => en_name, :jp_name => jp_name)
      a.conference_tag = conference_tag
      # We have to skip validations on Author because Author will
      # validate for the presence of a Submission, which we can 
      # only give it after saving an Authorship.
      a.save(:validate => false)
      self.author = a
      # We need a reload so that author recognizes its Authorships
      author.reload
    end
  end

  def uniquify_affiliations
    self.affiliations = affiliations.uniq
  end

  def destroy_author_if_orphan
    if author.authorships.empty?
      author.destroy
    end
  end

  def affiliation_institutes_are_set
    institutions_count = submission.institutions.size
    affiliations.each do |affiliation|
      unless institutions_count >= affiliation && affiliation > 0
        if (batch_import || author && author.batch_import || submission && submission.batch_import)
          raise "Bad affiliations_string for submission: #{submission.institutions.inspect} author: #{author.name} affiliations: #{affiliations.join(',')}"
        end
        errors.add(:affiliations_string, "は所属に含まれていない番号があります。")
        break
      end
    end
  end

  def name_is_set
    if en_name.blank? && jp_name.blank?
      errors.add(:en_name, "英語名もしくは日本語名は必須です。")
    end
  end

  def en_name_format
    if conference.config('validate_name_format_in_authorships')
      if (en_name.present? && en_name !~ /^(?:\p{Latin}|[-\.,\(\) ])+$/)
        errors.add(:en_name, "はアルファベット以外の文字が含まれまれています。")
      end
      if (en_name.present? && en_name !~ /[ ]/)
        errors.add(:en_name, "はfirst nameとlast nameをスペースで区切ってください。")
      end      
    end
  end

  def jp_name_format
    if conference.config(:validate_name_format_in_authorships)
      if (jp_name.present? && jp_name !~ /[ 　]/)
        errors.add(:jp_name, "は姓と名をスペースで区切ってください。")
      end
    end
  end

  def sync_author_if_requested_and_only_authorship_on_author
    if author && author.authorships.size == 1 && _sync_author_names
      # Inside a callback, you should be better use persistence
      # methods that will always work. This is because they won't
      # raise errors for you unless you are explicit.
      #
      # For example, using #save! in a callback will raise a RecordInvalid exception
      # but if the record was saved with #save, then that will consume
      # the RecordInvalid exception. You simply cannot expect the exception
      # to bubble up reliably, so the best you can do is to add an ActiveModel::Errors,
      # which can be a bit complicated in it's own right if we are doing nested stuff.
      # 
      # If we want to raise an error, raise something explicit. Otherwise,
      # make sure that the callback won't fail.
      #
      # You could also test if the return value is nil, but that's not always good.
      author.update_column(:en_name, en_name)
      author.update_column(:jp_name, jp_name)
    end
  end

  def require_email_in_authorships
    return !!conference.config('require_email_in_authorships')
  end
end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController
  authorize_resource
  respond_to :html, :js
  include Kamishibai::ResponderMixin
  
  # GET /authorships/new
  # GET /authorships/new.json
  def new
    @authorship = Authorship.new
    if params[:author_id]
      @authorship.author = Author.find(params[:author_id])
    end
    if params[:submission_id]
      @authorship.submission = Submission.find(params[:submission_id])
    end

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /authorships/1/edit
  def edit
    @authorship = Authorship.find(params[:id])
  end

  # POST /authorships
  # POST /authorships.json
  def create
    @authorship = Authorship.new(params[:authorship])
    @authorship.conference_confirm = current_conference

    respond_to do |format|
      if @authorship.save
        flash[:notice] = 'Authorship was successfully created.'
        format.html { js_redirect ksp(@authorship) }
      else
        flash[:error] = "Error in input"
        format.html { render action: "new" }
      end
    end
  end

  def drop_on_submission
    @submission = Submission.in_conference(current_conference).find(params[:authorship][:submission_id])
    if (url = params[:data_transfer]['text/plain'] || url = params[:data_transfer]['text/html']) && 
       url =~ /authors\/(\d+)/
      @author = Author.in_conference(current_conference).find($1)
      @authorship = @submission.authorships.build(:author_id => @author.id)
      @authorship.skip_affiliations_validation = true
    end

    if @authorship && @authorship.save
      flash[:notice] = "Authorship was successfully created"
    else
      flash[:error] = "Failed to create Authorship"
    end

    respond_to do |format|
      format.html { 
        render :partial => "authorships/list", :locals => {:authorships => @submission.authorships.order(:position)}
      }
    end
  end

  # PUT /authorships/1
  # PUT /authorships/1.json
  def update
    @authorship = Authorship.in_conference(current_conference).find(params[:id])
    @authorship.conference_confirm = current_conference

    # respond_to do |format|
      if @authorship.update_attributes(params[:authorship])
        flash[:notice] = 'Authorship was successfully updated.'
        # format.html { render action: "edit" }
        # format.html { redirect_to @authorship, notice: 'Authorship was successfully updated.' }
      else
        flash[:error] = 'Failed to update Authorship.'
        # format.html { render action: "edit" }
      end
    # end
    respond_with @authorship, :success_action => :back
  end

  # DELETE /authorships/1
  # DELETE /authorships/1.json
  def destroy
    @authorship = Authorship.in_conference(current_conference).find(params[:id])
    if @authorship.destroy
      flash[:notice] = "Authorship was successfully destroyed."
    else
      flash[:error] = "Failed to destroy Authorship #{@authorship.errors.full_messages}"
    end

    respond_with @authorship, :success_action => :back, :action => :edit
  end

  # POST /authorships
  def sort
    unordered_authorships = Authorship.in_conference(current_conference).find(params[:authorship_list])
    @authorships = params[:authorship_list].map{|as_id| 
                     unordered_authorships.detect{|ua| ua.id == as_id.to_i}}
    Authorship.transaction do
      @authorships.each_with_index do |as, i|
        as.position = i + 1 # acts_as_list starts with position 1
        as.save!(validate: false)
      end
    end
    respond_to do |format|
      format.html { render :partial => "list", :locals => {:authorships => @authorships}}
    end
  end
end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/views/authorships/_form.html.haml
= form_for @authorship, :remote => true,
           :data => {:ks_insert_response => true} do |f|
  - if @authorship.errors.any?
    #error_explanation
      %h2
        = pluralize(@authorship.errors.count, "error") 
        prohibited this authorship from being saved:

      %ul
        - @authorship.errors.full_messages.each do |msg|
          %li
            = msg
  %fieldset
    %legend Submission information
    .field
      = f.label :submission_id
      = f.hidden_field :submission_id
      %br/
      = link_to "#{@authorship.submission.submission_number}: #{@authorship.submission.jp_title} #{@authorship.submission.en_title}",
                ksp(:edit_submission_path, @authorship.submission) if @authorship.submission
  %fieldset
    %legend Author information as shown on Presentation
    .field
      = f.label :jp_name
      %br/
      = f.text_field :jp_name, :style => "width: 600px"
    .field
      = f.label :en_name
      %br/
      = f.text_field :en_name, :style => "width: 600px"
    / .field
    /   = f.label :position
    /   %br/
    /   = f.number_field :position
    .field
      = f.label :is_presenting_author
      %br/
      = f.check_box :is_presenting_author
    .field
      = f.label :affiliations
      - @authorship.submission.institutions.each_with_index do |inst, i|
        %div
          = hidden_field_tag "authorship[affiliations][]", ""
          = check_box_tag "authorship[affiliations][]", i + 1, @authorship.affiliations.include?(i + 1)
          = "#{i + 1}) #{inst.name}"
    .actions
      = f.submit

  %fieldset
    %legend このAuthorshipは次の著者Authorと関連しています
    .field
      = f.label :author_id
      = f.number_field :author_id
    .field
      = "#{@authorship.author.jp_name} #{@authorship.author.en_name}"
      = link_to "[edit]", ksp(edit_author_path(@authorship.author)) if @authorship.author
      %br/
      = link_to "[Create new Author for this Authorship]", ksp(new_author_path(:initial_authorship => @authorship)), :target => "_new_author"
    .field
      = @authorship.author.all_unique_affiliations.sort.to_a.join('<br />').html_safe
    %div{:style => "border: #666 1px dotted"}
      :markdown
        Drag an author URL or an author element here to change author

app/views/authorships/_list.html.haml
#authorship_list.sortable{:data => {:action => sort_authorships_path}}
  - authorships.each do |as|
    %div{:draggable => "true", :id => "authorship_#{as.id}"}
      ⇅
      %div{style:"display:inline-block;width:110px"}
        Authorship:
        = "◯" if as.is_presenting_author
      = link_to "#{as.en_name} | #{as.jp_name}", ksp(:edit_authorship_path, as)
      != "(" + as.affiliations.map{|aff| content_tag :span, "#{aff}", 
                                         :class => "color_#{aff - 1}"}.join(', ') + ")"
      %div{style:"padding-left:20px"}
        %div{style:"display:inline-block;width:110px"}
          Author:
        = link_to "#{as.author.en_name} | #{as.author.jp_name}", ksp(:edit_author_path, as.author)

app/views/authorships/edit.html.haml
= ks_element :id => "edit_authorship",
             :data => {:container => "ponzu_frame",
                       :container_ajax => static_path('ponzu_frame')} do
  .panel
    %h1 Editing authorship
    :markdown
      ### What are Authorships
      Authorships describe the relationship between Authors and Submissions. Use this page to change how the author information will be displayed on each Presentation page. To change how it will be displayed on the Author page, go to the Edit Author page.

      * Edit the Author Jp name and En name as it will appear on the Presentation information. This may be different from what is displayed on the Author profile page.
      * If the Author is the presenting author for this submission, then check the presenting Author.
      * Select Affiliations for the author. Editing the affiliations can be done on the Submission page.
    = render 'form'

    = link_to 'Delete authorship', @authorship, :method => :delete, :confirm => "Are you sure you want to delete this authorship?", :remote => true

app/views/authorships/new.html.haml
= ponzu_frame do
  %h1 New authorship
  = render 'form'
  = link_to 'Back', authorships_path
  |
  = link_to 'New User', new_user_path, :target => "_blank"