config/routes.rb
Rails.application.routes.draw do

  resources :conferences do
    collection do
      get :notifications
      post :delegate
    end
  end

  resources :messages

  match "/manifest" => "dashboard#cache_manifest"
  
  resources :authors do
    member do
      post :replace
    end
  end

  resources :submissions do
    member do
      put :update_institutions
    end
  end
  
  resources :umin_rows

  resources :meet_up_comments

  resources :participations

  resources :meet_ups do
    member do
      put 'participate'
    end
  end

  resources :global_messages
  
  resources :receipts do
    collection do
      put 'mark_read_by_sender'
      put 'mark_read'
      put 'mark_unread'
    end
  end

  resources :likes do
    collection do 
      get 'by_day'
      post 'batch_request_likes'
      post 'vote'
      get 'my_votes'
      get 'likes_report'
      get 'votes_report'
    end
    member do
      get 'my'
      get 'my_schedule'
      put 'schedulize'
      put 'unschedulize'
      put 'secretify'
    end
  end

  get "user_sessions/new"

  get "browser(/:session_id)" => "browser#list", :as => :list_browser

  get "browser/details/:presentation_id" => "browser#details"
  
  get "login" => "user_sessions#new", :as => :login
  get "logout" => "user_sessions#destroy", :as => :logout

  get "schedule" => "schedule#index"

  resources :pages

  resources :authorships do
    collection do
      post 'sort'
      post 'drop_on_submission'
    end
  end

  resources :comments do
    member do
      get 'reply'
    end
  end

  resources :rooms do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  
  resources :poster_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end
    collection do
      get 'container'
    end
  end

  resources :booth_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end    
  end
  
  resources :timetable do
    member do
      get 'like_highlights'
      get 'list'
    end
    collection do
      get 'container'
    end
  end
  
  resources :dashboard do
    collection do
      get 'liked_presentations_ajax'
      get 'my_presentations_ajax'
      get 'scheduled_presentations_ajax'
      get 'private_messages_ajax'
      get 'meet_ups_ajax'
      get 'global_messages_ajax'
      get 'notifications'
      get 'global_messages'
      get 'my_presentations'
      get 'my_meet_ups'
      get 'private_messages'
      get 'social_links'
      post 'batch_request_pages'
    end
  end
  
  resources :sessions do
    member do
      get 'detail'
      get 'poster_row'
      get 'social_box'
      get 'poster_social_box'
      get 'download_pdf'
      get 'download_full_day_pdf'
      put 'order_presentations_by_number'
      put 'set_presentation_duration'
      get 'query'
      put 'change_children_presentation_types'
    end
    collection do
      post 'batch_request_liked_sessions'
      get 'download_full_pdf'
      get 'download_pdf_by_name'
    end
  end

  resources :presentations do
    member do
      get 'next'
      get 'previous'
      get 'likes'
      get 'comments'
      get 'social_box'
      put 'toggle_schedule'
      post 'create_comment'
      get 'related'
      get 'heading'
      put 'change_ad_category'
    end
    collection do
      get 'my'
      post 'sort'
      post 'batch_request_likes'
    end
  end

  resources :users do
    member do
      put 'set_global_message_to_read'
      put 'reset_read_global_messages'
      get 'settings', :to => 'users#settings'
      put 'settings', :to => 'users#update_settings'
      get 'edit_name'
      put 'update_name'
      get 'admin_panel'
      put 'assign_author'
    end
    collection do
      get 'admin_search'
      get 'admin_search_by_registration_id'
    end
  end
  
  resources :user_sessions do
    collection do
      post 'switch'
    end
  end
  
  resources :private_messages do
    collection do
      get 'threads'
    end
  end

  match 'private_messages/conversation/:with' => 'private_messages#conversation', :as => 'conversation_private_messages'

  resources :search

  match 'docs/batch' => 'docs#batch', :as => "docs_batch"
  match 'docs/test_batch' => 'docs#test_batch', :as => "docs_test_batch"
  match 'docs(/:folder)/manifest' => 'docs#manifest', :as => "docs_manifest"
  match 'docs/:page(/:sub_page)' => 'docs#show', :as => "docs", :via => [:get]
  match 'docs/:page(/:sub_page)' => 'docs#create', :as => "docs", :via => [:post]
  match 'docs(/)' => 'docs#index', :as => "docs_root"

  match 'tests/:page(/:sub_page)' => 'tests#show', :as => "tests", :via => [:get]

  match 'admin/:action' => 'admin', :as => "admin"

  match ':page' => 'static#show', :as => :static, 
        :constraints => {:page => /ponzu_frame|ponzu_admin_frame|rake_reports/}

  match 'system/ks_cache_version' => "conferences#ks_cache_version", :as => :ks_cache_version

  root :to => 'static#layout'

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  # We used to use this controller for tests so we have
  # a "docs" layout. We don't use it here so we change it.
  layout "application"
  # This allows us to use docs_controller for full HTML responses (not XHR)
  before_filter :ignore_default_kamishibai_hash_tag
  set_kamishibai_expiry [:show] => 24 * 60 * 60
  @@action_sanitize_regex = /[^0-9a-zA-Z_-]/

  # TODO: Think about doing this to make it easy to render markdown
  # http://stackoverflow.com/questions/4163560/how-can-i-automatically-render-partials-using-markdown-in-rails-3/4418389#4418389
  def show
    action = action_string
  	respond_to do |format|
  		format.html{
        if request.xhr?
          render :action => action, :layout => false
        else
          if galapagos?
            render :action => action, :layout => "layouts/galapagos"
          else
            render :action => action
          end
        end
      }
    end
  end

  # for testing post reqeusts
  def create
    action = action_string
    respond_to do |format|
      format.html{
        if request.xhr?
          render :action => action, :layout => false
        else
          render :action => action
        end
      }
    end
  end

  def index
  end

  # Since we contain user specific information in the top page, and we 
  # need to cache that page, we have to think about how we handle login
  # and logouts with the cache_manifest.
  # Refer to the Numbers file cachemanifest_scheme.numbers
  def manifest
    action = [params[:folder], "manifest"].join("/")
    headers['Cache-Control'] = "max-age=0, no-cache, no-store, must-revalidate"
    headers['Pragma'] = "no-cache"
    headers['Expires'] = "Wed, 11 Jan 1984 05:00:00 GMT"
    headers['Content-Type'] = "text/cache-manifest"
    render :action => action, :layout => false
  end


  def batch
    responses = {}
    pages = ["mockup", "mockup2", "ponzu", "showcase", "tests"]

    pages.each do |page|
      path = File.expand_path("#{page}", "#{__FILE__}/../../views/docs/");
      all_html_files = Dir.entries(path).delete_if{|e| e !~ /\.html\./}.map{|e| e.sub(/\.html\..*$/, "")}

      all_html_files.each do |sub_page|
        url = docs_path("#{page}/#{sub_page}")
        body = run_action(:show, {page: page, sub_page: sub_page}, {xhr: true})
        responses[url] = body
      end
    end
    render :json => responses
  end

  # Test to load a huge number of pages
  # Test results:
  # After the JSON response has been received, loading up the
  # database returns immediately because database actions are asynchronous.
  # However, database queries have simply queued up meaning that subsequent
  # requests to the database (and hence all page transitions) simply wait.
  # One way is to make sure that we don't wait on the database while doing
  # page transitions (but the issue is that we want to know the cache) state
  # in order to set timeout.
  # A Load button makes a lot of sense but it has to work with the asynchronous interface.
  def test_batch
    responses = {}
    page = "showcase"
    sub_page = "introduction"
    1.upto(1000) do |i|
      url = docs_path("#{page}/#{sub_page}")
      body = run_action(:show, {page: page, sub_page: sub_page}, {xhr: true})
      responses["#{url}_#{i}"] = body      
    end
    render :json => responses
  end

  private

  def action_string
    [params[:page], params[:sub_page]].map{|s| s.gsub(@@action_sanitize_regex, '_')}.join('/')
  end

end

app/views/docs/ponzu_demo/child_care.html.haml
= ponzu_frame do
  .panel
    :markdown
      ## 第 46 回日本発生生物学会年会 保育室のご案内
      
      保育室の利用を希望される方は、以下の規定を御確認の上、所定の手続き方法に従って日本語でお申込ください。なお保育士は英語を話せません。

      ### 託児時間

      5 月 29 日(水) 8:00 ~ 20:00  
      5 月 30 日(木) 8:00 ~ 19:00  
      5 月 31 日(金) 8:00 ~ 16:00  
      (*原則としてお子様の昼食は、保護者が一緒におとりください。)

      ### 対象年齢
      生後 3 ヶ月から 12 歳まで(大会参加者のお子様に限る)

      ### 託児場所
      ※セキュリティ確保の為、お申込者のみにご案内致します。

      ### 託児形態
      託児の会へ保育士派遣を依頼します。

      ### 委託先
      ちゅうりっぷ託児の会

      ### 託児料
      500 円/時間/お子さま 1 名(1 時間未満は切上げ)  
      保育料のお支払いは、お子様をお預けの際にお願いします。  
      *申込みによりシッターが派遣されますので、当日のキャンセルや、実際の利用時間 が申込時間よりも短くなった場合は、申込時の保育料のお支払いをお願いします。また、 利用時間をやむを得ず延長された場合には、延長分のお支払いをお願いします。

      ### 申込み先

      「利用規約(PDF94KB)」を確認のうえ、必要事項を記入した「申込書(PDF84KB)」 を FAX または E メールにてお申し込みください。 
      
      1. 後日、詳細を記載しました「受領確認書」をお申し込み頂いた方法で返信します。  
      お申し込み後一週間以内に受領確認書が届かない場合には、下記の「申し込み先・お問い合わせ先」まで必ずお問い合わせください。 

      ※ 保育室の場所は、受領確認書に記載させていただきます。  
      ※ 電話での受付は 078-306-3072(平日 9:00 ~ 17:00)   
      ■申し込み先・お問い合わせ先  
      日本発生生物学会 事務局  
      担当:桃津  
      FAX: 078-306-3072  E-mail: jsdb2013@jsdb.jp TEL: 078-306-3072(平日 9:00 ~ 17:00)

      ### 申込締切

      **2013年5月8日(水)17時00分**  
      ただし、定員になり次第締め切らせて頂きますのでお早めにお申込み下さい。

      ---------

      不測の事故に対応するために、ちゅうりっぷ託児の会が保険に加入しており、保険適用範囲で補償い たします、また第 46 回日本発生生物学会年会は、事故の責任は負わないことを申し添えます。

app/views/docs/ponzu_demo/pdfs.html.haml
- cache ["v1", current_conference, I18n.locale, "pdfs"] do
  = ponzu_frame do
    .panel
      / = image_tag 'jsdb2013/takashi_matsuzaki.jpg', 
      /             :style => "float:left;margin: 0 10px 10px 0;border: solid 0px #FFF;box-shadow: 1px 1px 4px #666"
      %h1
        = image_tag "ponzu/pdficon_72.png", :style => "vertical-align: middle"
        = "Download PDFs"

    .panel_title Program
    .panel
      = render :partial => "dashboard/button_grid", 
          :locals => {:types => [:pdf_with_abstract]}
    .panel_title Each Session (50 - 400KB)
    .pdf_list
      - sessions = []
      - {"Plenary Lectures" => '^PL', "Luncheon Seminars" => '^L[0-9]', "Symposium" => '^S[0-9]', 
         "Oral Presentations" => '^OP', "Flash Talks" => '^FT', "Satellite Symposium" => '^SS', 
         "Poster Presentations" => '^P[0-9]', "Late Breaking Abstracts" => '^LBA', 
         "Satellite Workshop" => '^SW', "Technical Workshop" => '^TW'}.each do |name, regex|
        .panel_title= name
        .paneled_list.panel
          - sessions = Session.where(%Q(number REGEXP '#{regex}')).order(:number).all
          - sessions.each do |s|
            = link_to download_pdf_session_path(s), :style => "overflow: hidden" do
              = image_tag("ponzu/pdficon_large.png", :style => "float:left; margin-right: 10px")
              %span.number= s.number
              = s.title

app/views/docs/ponzu_demo/speaker_instructions.html.haml
= ponzu_frame do
  .panel
    :markdown
      <h1>Instruction for Presentations<br /></h1>
      <br>
      <b>Oral presentations</b><br>
      We generally recommend that speakers use their own PCs for their presentations. Please come to your session room at least 30 min prior to the beginning and connect your PC to a PC switcher. Alternatively, you can also use organizer-provided PCs in the conference rooms, but we do not guarantee device compatibility for each file. Although we can accept data from a USB flash drive or a CD-ROM, it is better to bring your data in at least 2 different methods. Slide projectors or overhead projectors will not be available.<br>
      <br>
      Oral presentation: 8 min for presentation and 4 min for discussion. <br>
      Flash Talk: 4 min presentation only.<br>
      Satellite Workshops: 10min presentation including discussion.<br>
      <br>
      <b>Attention: Personal computer information</b><br>
      The operating systems of the computer at the meeting venue are Window 7 and Mac OS X 10.6. <br>
      <br>
      Windows format files: <br>
      - Please copy your data onto a USB flash drive or a CD-ROM (Windows format). <br>
      - The system can support Windows PowerPoint 2003, 2007, and 2010. <br>
      - To avoid undesired changes of the slide layouts, we recommend using the following fonts: MS Gothic, MS Mincho, Times New Roman, or Century. <br>
      <br>
      Macintosh format files: <br>
      - Please copy your data onto a USB flash drive or CD-ROM (Macintosh format). <br>
      - The system can support Macintosh PowerPoint 2004, 2008, and 2011; and Keynote 3, 4, and 5. <br>
      - Please use standard fonts installed in the program. <br>
      - If your presentation includes movies, please confirm beforehand that they can run properly on another computer. We recommend bringing your own computer to the venue as a backup. <br>
      <br>
      * If your presentation includes movies, please confirm beforehand that they can run properly on another computer, or use your own PC.<br>
      <br>
      For using your own PC:<br>
      - We accept Windows (Windows XP or later) or Macintosh (Mac OSX or later) PCs. <br>
      - You can use PowerPoint (Windows, Mac) or Keynote (Mac) for presentation. <br>
      - Make sure to bring any necessary electrical adaptors and connectors for your computer. <br>
      - The meeting venue will provide a Mini D-sub15 pin cable for connecting to PC switchers. Macintosh and certain kinds of Windows computers require an appropriate connector to fit a Mini D-sub15 pin plug. <br>
      - Electric power in Matsue is provided at 100V, 60Hz.<br>
      - In case your computer does not work, please bring your backup files on a USB flash drive or a CD-ROM.<br>
      <br>
      <br>
      <b>Poster Presentations</b><br>
      Poster board size: 1200 mm (width) x 2100 mm (height)<br><br>
      • Please leave a 150 mm x 150 mm blank space at the top left corner for the organizing committee to indicate your poster number.<br>
      • During your assigned poster presentation time, please stay (or stand) in the vicinity of your poster for explanation.<br>
      • Best Presentation Awards will be given for several student presenters. Award winners will be selected using the web voting system by capable participants of the meeting, and will be announced after the meeting.<br>
      <br>
      <b>Poster: </b><br>
      Mounting: 9:00 - 13:00 on 29 May<br>
      Discussion:17:00 - 19:00 on 30 May<br>
      　　　 　　　　　 17:00 -18:00 for even number posters<br>
      　　　 　　　　　 18:00 - 19:00 for odd number posters<br>
      Removal: 12:00 - 16:00 on 31 May<br>
      <table>
      <tbody><tr><td>
      <img src="#{asset_path('jsdb2013/posternumber.jpg')}" width="350" height="400">
      </td></tr>
      </tbody></table>
      <br>
      <b>Chairpersons</b><br>
      All chairpersons are required to come to their assigned session rooms at least 30 min prior to the start of the session they will chair.<br>

app/views/docs/ponzu_demo/welcome.html.haml
= ponzu_frame :data => {:title => "JSDB2013: Welcome"} do
  .panel
    = image_tag 'ponzu/GodfreyKneller-IsaacNewton-1689_256.jpg', 
                :style => "width: 30%;max-width: 128px;max-height: 128px;float:left;margin: 0 10px 10px 0;border: solid 0px #FFF;box-shadow: 1px 1px 4px #666;"
    %h1{:style => "font-size: 30px;line-height:30px;"} Welcome to the Ponzu Demo website
    %div{:style => "clear:both"}
    %div.text.auto-hyphen
      :markdown
        Thank you for visiting this Ponzu Demo website. 

        This demo showcases the Ponzu Scientific Conference System. Almost all features are available to explore. Please play around and get to know the system.

        We hope that you will find it to be truly revolutionary and immensely exciting.

        ## What is Ponzu?

        Ponzu(ポン酢) is a Japanese word for a citrus-based refreshing Japanese sauce. The Japanese use it as a dip for meaty dishes like shabu-shabu. Ponzu conceals the greasy taste of fat, making the meat more pleasant to eat and boosting our appetites.

        Similarly, the Ponzu Scientific Conference System aims to make the *meat* of the conference (the presentations and heated discussions) more exciting, refreshing and more savory.

        Ponzu evolved from the online abstract system for the 35th Annual Meeting of the Molecular Biology Society of Japan ([website](http://www2.convention.co.jp/mbsj2012/). The information system itself is offline.). The program has been released as open source, and is free for anyone to use. Castle104 is commited to improving the system going forward.

        ## Ponzu is Social
        In science we have "societies" and "communities". The largest scientific group in Japan calls itself "The Molecular Biology Society of Japan", for example. Hence scientific conferences are in essence, social and communal events.

        Ponzu builds upon this basic concept. We have brought ideas from the Social Internet (i.e. Facebook, Twitter) and incorporated them into the Ponzu Scientific Conference System.

        Our hope is that by enhancing the *social* factor and causing scientists of varied geographical locations and research interests to know each other, we can promote learning and innovation.

        ### Likes

        For example, Ponzu has "likes". "Likes" are a way communicating appreciation for a presentation. The system itself is similar to bookmarks and favorites that are common on other conference systems, but with one vitally important difference; the speaker and co-authors can view a list of everybody who "liked".

        This feature opens up a variety of possible exciting scenarios. For example, a speaker could view the "likes" before their presentation, look up their profiles and gain an understanding of the audience. Additionally, if you find a "liker" whom you are interested in collaborating with, you could use the Ponzu system to send them a message and meet up at the venue.

        My favorite scenario is when a renown scientist "likes" a presentation by an aspiring one. The aspiring scientist may be hugely encouraged and could follow up, asking the renown scientist's opinion and maybe ask for a job opportunity.

        ## Ponzu is about attending

        Ponzu is about the physical conference and face-to-face communications. Unlike other IT solutions like video streaming, Ponzu is completely focused on the experience on the ground, at the conference venue.

        One example of our focus on attending is our revolutionary approach to poster navigation.

        That is why we have created the world's first interactive poster map system, which makes it vastly easier to navigate the often huge poster sessions within the limited time.

        It is also why we have Yoruzemi, a bulletin board system to 

    %p
      %br/
      %br/
      Chief architect and developer of Ponzu
      %br/
      %br/
      Naofumi Kagami
      %br/
      Castle104, LLC