config/routes.rb
Rails.application.routes.draw do

  resources :conferences do
    collection do
      get :notifications
      post :delegate
    end
  end

  resources :messages

  match "/manifest" => "dashboard#cache_manifest"
  
  resources :authors do
    member do
      post :replace
    end
  end

  resources :submissions do
    member do
      put :update_institutions
    end
  end
  
  resources :umin_rows

  resources :meet_up_comments

  resources :participations

  resources :meet_ups do
    member do
      put 'participate'
    end
  end

  resources :global_messages
  
  resources :receipts do
    collection do
      put 'mark_read_by_sender'
      put 'mark_read'
      put 'mark_unread'
    end
  end

  resources :likes do
    collection do 
      get 'by_day'
      post 'batch_request_likes'
      post 'vote'
      get 'my_votes'
      get 'likes_report'
      get 'votes_report'
    end
    member do
      get 'my'
      get 'my_schedule'
      put 'schedulize'
      put 'unschedulize'
      put 'secretify'
    end
  end

  get "user_sessions/new"

  get "browser(/:session_id)" => "browser#list", :as => :list_browser

  get "browser/details/:presentation_id" => "browser#details"
  
  get "login" => "user_sessions#new", :as => :login
  get "logout" => "user_sessions#destroy", :as => :logout

  get "schedule" => "schedule#index"

  resources :pages

  resources :authorships do
    collection do
      post 'sort'
      post 'drop_on_submission'
    end
  end

  resources :comments do
    member do
      get 'reply'
    end
  end

  resources :rooms do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  
  resources :poster_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end
    collection do
      get 'container'
    end
  end

  resources :booth_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end    
  end
  
  resources :timetable do
    member do
      get 'like_highlights'
      get 'list'
    end
    collection do
      get 'container'
    end
  end
  
  resources :dashboard do
    collection do
      get 'liked_presentations_ajax'
      get 'my_presentations_ajax'
      get 'scheduled_presentations_ajax'
      get 'private_messages_ajax'
      get 'meet_ups_ajax'
      get 'global_messages_ajax'
      get 'notifications'
      get 'global_messages'
      get 'my_presentations'
      get 'my_meet_ups'
      get 'private_messages'
      get 'social_links'
      post 'batch_request_pages'
    end
  end
  
  resources :sessions do
    member do
      get 'detail'
      get 'poster_row'
      get 'social_box'
      get 'poster_social_box'
      get 'download_pdf'
      get 'download_full_day_pdf'
      put 'order_presentations_by_number'
      put 'set_presentation_duration'
      get 'query'
      put 'change_children_presentation_types'
    end
    collection do
      post 'batch_request_liked_sessions'
      get 'download_full_pdf'
      get 'download_pdf_by_name'
    end
  end

  resources :presentations do
    member do
      get 'next'
      get 'previous'
      get 'likes'
      get 'comments'
      get 'social_box'
      put 'toggle_schedule'
      post 'create_comment'
      get 'related'
      get 'heading'
      put 'change_ad_category'
    end
    collection do
      get 'my'
      post 'sort'
      post 'batch_request_likes'
    end
  end

  resources :users do
    member do
      put 'set_global_message_to_read'
      put 'reset_read_global_messages'
      get 'settings', :to => 'users#settings'
      put 'settings', :to => 'users#update_settings'
      get 'edit_name'
      put 'update_name'
      get 'admin_panel'
      put 'assign_author'
    end
    collection do
      get 'admin_search'
      get 'admin_search_by_registration_id'
    end
  end
  
  resources :user_sessions do
    collection do
      post 'switch'
    end
  end
  
  resources :private_messages do
    collection do
      get 'threads'
    end
  end

  match 'private_messages/conversation/:with' => 'private_messages#conversation', :as => 'conversation_private_messages'

  resources :search

  match 'docs/batch' => 'docs#batch', :as => "docs_batch"
  match 'docs/test_batch' => 'docs#test_batch', :as => "docs_test_batch"
  match 'docs(/:folder)/manifest' => 'docs#manifest', :as => "docs_manifest"
  match 'docs/:page(/:sub_page)' => 'docs#show', :as => "docs", :via => [:get]
  match 'docs/:page(/:sub_page)' => 'docs#create', :as => "docs", :via => [:post]
  match 'docs(/)' => 'docs#index', :as => "docs_root"

  match 'tests/:page(/:sub_page)' => 'tests#show', :as => "tests", :via => [:get]

  match 'admin/:action' => 'admin', :as => "admin"

  match ':page' => 'static#show', :as => :static, 
        :constraints => {:page => /ponzu_frame|ponzu_admin_frame|rake_reports/}

  match 'system/ks_cache_version' => "conferences#ks_cache_version", :as => :ks_cache_version

  root :to => 'static#layout'

end

app/models/meet_up.rb
# encoding: UTF-8

class MeetUp < ActiveRecord::Base
  attr_accessible :description, :meet_at, :starts_at, :venue, 
                  :venue_url, :title, :starts_at_date, :starts_at_hour, 
                  :starts_at_minute, :interest, :venue_phone, :owner_phone
  has_many :participations, :dependent => :destroy, :inverse_of => :meet_up
  has_many :participants, :through => :participations, :source => :user
  belongs_to :owner, :class_name => 'User'

  has_many :meet_up_comments, :inverse_of => :meet_up, :dependent => :destroy
  validates_presence_of :owner_id, :title
  before_validation :set_starts_at
  validates_presence_of :starts_at
  after_save   :notify_participants_of_changes

  include ConferenceRefer
  validates_conference_identity :owner

  include ConferenceDates
    
  def starts_at_date
    starts_at && starts_at.strftime('%Y-%m-%d')
  end
  
  def starts_at_date= (date)
    @starts_at_date = date
    # starts_at.change(:day => day)
  end
  
  def starts_at_hour
    starts_at && (starts_at.hour)
  end

  def starts_at_hour= (hour)
    @starts_at_hour = hour.to_i
  end
  
  def starts_at_minute
    starts_at && starts_at.min
  end

  def starts_at_minute= (minute)
    @starts_at_minute = minute.to_i
  end
  
  def set_starts_at
    if @starts_at_date && @starts_at_hour && @starts_at_minute
      self.starts_at = Time.zone.parse("#{@starts_at_date}").
                       change(:hour => @starts_at_hour.to_i,
                              :min => @starts_at_minute.to_i)
    end
  end
  
  def venue_url=(url)
    if url !~ /^http/
      url = "http://" + url
    end
    self[:venue_url] = url
  end

  def toggle_participation(user)
    participate?(user) ? participants.destroy(user) :
                         participants << user
  end
  
  def participate?(user)
    user && participants.include?(user)
  end

  def participation_for_user(user)
    user && participations.detect{|p| p.user == user}
  end
  
  def notify_participants_of_changes
    # send_message (participants + users_who_commented - [owner]).uniq, changes_message, "Yorusemi #{self.title} was changed"
    # send_message owner, changes_message, "Yorusemi #{self.title} was changed"
  end
  
  def users_who_commented
    meet_up_comments.map{|c| c.user}
  end
  
  def changes_message
    [ "Title: #{title}",
      "Starts at: #{starts_at.strftime('%m/%d %H:%M')}",
      "Place: #{venue}",
      "Owner: #{owner.name}",
      "Owner contact: #{owner_phone}",
      "Place URL: #{venue_url}",
      "Place phone: #{venue_phone}",
      "Description: #{description}"].join("\n")
  end
  
  # Interface for mailboxer
  def name
    title
  end
end

app/controllers/meet_ups_controller.rb
class MeetUpsController < ApplicationController
  authorize_resource :except => [:index, :show]
  respond_to :html, :js
  include Kamishibai::ResponderMixin

  set_kamishibai_expiry [:index, :show] => 1

  before_filter do |c|
    @menu = :meet_ups
  end

  # GET /meet_ups
  # GET /meet_ups.json
  def index
    @show_date = params[:date] ? Time.parse(params[:date]) :
                                 current_conference.closest_date_for(:meet_up, Time.zone.now)
    @meet_ups = MeetUp.where("? < starts_at AND starts_at < ?",
                        @show_date.beginning_of_day,
                        @show_date.end_of_day).paginate(:page => params[:page]).
                       in_conference(current_conference)
    
    respond_with @meet_ups
  end

  # GET /meet_ups/1
  # GET /meet_ups/1.json
  def show
    @meet_up = MeetUp.in_conference(current_conference).
                      find(params[:id])

    respond_with @meet_up
  end

  # GET /meet_ups/new
  # GET /meet_ups/new.json
  def new
    @meet_up = MeetUp.new

    respond_with @meet_up
  end

  # GET /meet_ups/1/edit
  def edit
    @meet_up = MeetUp.in_conference(current_conference).
                      find(params[:id])
    if @meet_up.owner_id != current_user.id
      raise CanCan::AccessDenied.new("Not authorized!", :read, @meet_up)
    end

    respond_with @meet_up
  end

  # POST /meet_ups
  # POST /meet_ups.json
  def create
    @meet_up = MeetUp.new(params[:meet_up])
    @meet_up.owner_id = current_user.id
    @meet_up.conference_confirm = current_conference

    if @meet_up.save
      flash[:notice] = "Successfully created Yoruzemi"
      ks_cache_invalidate [meet_ups_path(:date => @meet_up.starts_at.strftime('%Y-%m-%d'))]
    else
      flash[:error] = "Failed to create Yoruzemi"
    end
    respond_with @meet_up
  end

  # PUT /meet_ups/1
  # PUT /meet_ups/1.json
  def update
    params[:meet_up].delete('owner_id')
    @meet_up = MeetUp.in_conference(current_conference).
                      find(params[:id])
    old_starts_at = @meet_up.starts_at
    if @meet_up.owner_id != current_user.id
      raise CanCan::AccessDenied.new("Not authorized!", :read, @meet_up)
    end

    if @meet_up.update_attributes(params[:meet_up])
      flash[:notice] = "Yoruzemi was successfully updated."
      # We also have to invalidate the old starts_at
      ks_cache_invalidate [meet_ups_path(:date => @meet_up.starts_at.strftime('%Y-%m-%d')),
                           meet_ups_path(:date => old_starts_at.strftime('%Y-%m-%d')) ]

    else
      flash[:error] = "Failed to update yoruzemi"
    end

    respond_with @meet_up
  end

  # DELETE /meet_ups/1
  # DELETE /meet_ups/1.json
  #
  # Currently, only admins can destory meet_ups
  def destroy
    @meet_up = MeetUp.in_conference(current_conference).
                      find(params[:id])
    @meet_up.destroy

    if @meet_up.destroyed?
      flash[:notice] = "Sucessfully destroyed meet up"
    else
      flash[:error] = "Failed to destroyed meet up"
    end
    respond_with @meet_up
  end
  
  # PUT /meet_ups/1/participate
  def participate
    @meet_up = MeetUp.in_conference(current_conference).
                      find(params[:id])
    @user = current_user
    @meet_up.toggle_participation(@user)
    
    respond_to do |format|
      if request.xhr?
        format.js { render :js => "kss.redirect('!_#{meet_up_path(@meet_up)}')"}
      elsif galapagos?
        format.html { redirect_to @meet_up }
      end
  end
  end
end

app/views/meet_ups/_day_radio_buttons.html.erb
<% dates.each do |date| %>
  <div style="display:inline-block">
    <%= f.radio_button :starts_at_date, to_date_string(date)%>
    <%= f.label "starts_at_date_#{to_date_string(date)}", l(date, :format => :month_day) %>
  </div>
<% end %>

app/views/meet_ups/_form.g.html.haml
= form_for(@meet_up) do |f|
  = render :partial => "layouts/error_messages", :locals => {:target => @meet_up}
  %h2= "Summary"
  %h3= t('meet_ups.fields.title')
  = f.text_field :title
  %h3= t('meet_ups.fields.description')
  = f.text_area :description
  %h2= "Start/Assembly time"
  = t('meet_ups.fields.event_day')
  = render :partial => 'day_radio_buttons', 
                 :locals => {:f => f, :dates => current_conference.dates_for('meet_up')}
  = t('meet_ups.fields.event_starts_at')
  %div{:class => "#{error_indicator(@meet_up, :starts_at)}"}
    = f.select :starts_at_hour, (17..23).to_a.map{|h| [h,h]}
    \: 
    = f.select :starts_at_minute, ['00', '15', '30', '45'].map{|m| [m,m]}
  %h2= "Bar/Assembly place"
  = "Place: "
  = f.text_field :venue
  %h2= t('meet_ups.fields.link')
  = t('meet_ups.fields.link_to_venue')
  = f.text_field :venue_url
  %h2= t('meet_ups.fields.organizer_contact')
  = t('meet_ups.fields.organizer_contact')
  = f.text_field :owner_phone
  = f.submit submit_message

app/views/meet_ups/_form.html.haml
= form_for(@meet_up, :remote => true, 
            :html => {:data => {'invalidates-keys' => invalidated_paths(@meet_up),
                                'ks-insert-response' => true}}) do |f|
  = render :partial => "layouts/error_messages", :locals => {:target => @meet_up}
  .panel_title= t('meet_ups.panel_titles.summary')
  .panel
    .grid
      .col-1-3
        = t('meet_ups.fields.title')
      .col-2-3
        = f.text_field :title, :class => "h2_input", 
                     :placeholder => t('meet_ups.placeholders.title')
    .grid
      = f.text_area :description, :class => "text_area",
                      :placeholder => t('meet_ups.placeholders.description')
  .panel_title= t('meet_ups.panel_titles.starts_at_or_assembly_time')
  .panel
    .grid
      .col-1-3
        = t('meet_ups.fields.event_day')
      .col-2-3{:class => "#{error_indicator(@meet_up, :starts_at)}"}
        = render :partial => 'day_radio_buttons', 
                 :locals => {:f => f, :dates => current_conference.dates_for('meet_up')}
    .grid
      .col-1-3
        = t('meet_ups.fields.event_starts_at')
      .col-2-3{:class => "#{error_indicator(@meet_up, :starts_at)}"}
        = f.select :starts_at_hour, (17..23).to_a.map{|h| [h,h]}
        \: 
        = f.select :starts_at_minute, ['00', '15', '30', '45'].map{|m| [m,m]}
  .panel_title= t('meet_ups.panel_titles.bar_or_assembly_place')
  .panel
    .grid
      .col-1-3
        = t('meet_ups.fields.venue')
      .col-2-3
        = f.text_field :venue, :class => "text_field", 
                           :placeholder => t('meet_ups.placeholders.venue')
  .panel_title= t('meet_ups.panel_titles.related_links')
  .panel
    .grid
      .col-1-3
        = t('meet_ups.fields.link_to_venue')
      .col-2-3
        = f.text_field :venue_url, :class => "text_field", 
                          :placeholder => t('meet_ups.placeholders.link_to_venue')
  .panel_title= t('meet_ups.panel_titles.organizer_contact')
  .panel
    .grid
      .col-1-3
        = t('meet_ups.fields.organizer_contact')
      .col-2-3
        = f.text_field :owner_phone, :class => "text_field", 
                          :placeholder => t('meet_ups.placeholders.organizer_contact')

  .panel{:style => "text-align:right"}
    = f.button nil, :class => "button icon approve big"

app/views/meet_ups/_meet_up_comments.html.haml
#meet_up_comments
  - @meet_up.meet_up_comments.each do |c|
    .comment{:id => "meet_up_comment_#{c.id}"}
      .comment_properties
        %strong= link_to c.user.name, ksp(c.user)
        &nbsp;&nbsp;
        = c.created_at.strftime('%m-%d %H:%M')
        - if c.user == current_user
          = link_to "[x]", c, :method => :delete, :remote => true, :confirm => t('meet_ups.alerts.confirm_delete_comment'), :data => {'ks-insert-response' => ""}        

      = auto_link c.content
  - if current_user
    = form_for(MeetUpComment.new(:meet_up_id => @meet_up.id), :remote => true,
                 :html => {:data => {"invalidates-keys" => invalidated_paths(@meet_up),
                                     "ks-insert-response" => ""}}) do |f|
      = f.hidden_field :meet_up_id
      = f.text_area :content
      = f.button t("meet_ups.submit_comment"), :class => "button icon comment"

app/views/meet_ups/_participate_button.html.haml
- if !current_user
  Please first login to register for participation.
  %span.signup_message= t('meet_ups.buttons.you_get_notifications_if_you_register')
  = link_to "Login", ksp(login_path), :class => 'signup_button button big'
    
- elsif @meet_up.participate? current_user
  - participation = @meet_up.participation_for_user(current_user)
  = link_to(participate_meet_up_path(@meet_up),
            :method => :put, :class => 'cancel_button button icon remove big',
            :remote => true, 
            "data-invalidates-keys" => invalidated_paths(participation),
            :confirm => t('meet_ups.alerts.do_you_really_want_to_cancel')) do
    = t('meet_ups.buttons.you_are_planning_to_attend_this_yorusemi')
  %br/
  %span.cancel_message= t('meet_ups.buttons.click_here_to_cancel')
- else
  - participation = @meet_up.participations.build
  = link_to(participate_meet_up_path(@meet_up),
            :method => :put, :class => 'signup_button button icon add big',
            :remote => true,
            "data-invalidates-keys" => invalidated_paths(participation),
            :confirm => t('meet_ups.alerts.confirm_participation')) do
    = t('meet_ups.buttons.click_here_to_attend_this_yorusemi')
  %br/
  %span.signup_message= t('meet_ups.buttons.you_get_notifications_if_you_register')

app/views/meet_ups/edit.g.html.erb
<%= render :partial => 'form.g', :locals => {:submit_message => "以上の内容で夜ゼミを更新する"} %>

app/views/meet_ups/edit.html.haml
= ponzu_frame do
  .settings_bg
    %h1 Edit Yoruzemi
    = render :partial => 'form', :locals => {:submit_message => "以上の内容で夜ゼミを更新する"}

app/views/meet_ups/index.g.html.haml
%h1 Yoruzemi #{l(@show_date, :format => :month_day)}
%p
  = t('meet_ups.about_yorusemi')
%h2 Create a new Yoruzemi
= link_to t('meet_ups.lets_make_a_new_yorusemi'), ksp(new_meet_up_path)
%h2 List of Yoruzemi
= ks_will_paginate
- if @meet_ups.all.empty?
  = t('meet_ups.empty_message')
- else
  - @meet_ups.each do |meet_up|
    %div
      .left
        = content_tag(:span, "★", :style => "color: #ffe109") if meet_up.participate?(current_user)
        = l(meet_up.starts_at, :format => :month_day_time)
      .right
        = t('meet_ups.fields.organizer')
        = meet_up.owner.name
    %div= link_to meet_up.title, meet_up, :class => ['entry']
    %p
      = meet_up.description
    = hr

app/views/meet_ups/index.html.haml
= ponzu_frame :id => ["meet_ups", to_date_string(@show_date)],
              :title_args => {:date => to_date_string(@show_date)} do
  .panel
    .button-group
      - current_conference.dates_for('meet_up').each do |day|
        = link_to l(day, :format => :month_day), 
                      ksp(meet_ups_path(:date => to_date_string(day))), 
                      :class => ['button', ('primary' if @show_date == day)]
  .panel
    = image_tag("#{conference_tag}/help.png", :style => "margin: 0 10px 10px 0;float:left;height:30px")
    %p
      = t('meet_ups.about_yorusemi')
      %div
        = link_to t('meet_ups.more'), "#", 
                  :onclick => "kss.toggle(document.getElementById('about_more'));return false;"
    %ol#about_more{:style => "display:none"}
      = t('meet_ups.about_more').html_safe
    = link_to t('meet_ups.lets_make_a_new_yorusemi'), ksp(new_meet_up_path), :class => "big button icon add"
  - if @meet_ups.all.empty?
    .panel
      = t('meet_ups.empty_message')
  - else
    .panel_title= t('meet_ups.panel_titles.list_of_yoruzemi')
    .panel.paneled_list.meet_ups
      = ks_will_paginate
      - @meet_ups.each do |meet_up|
        = link_to ksp(url_for(meet_up)), 
                  :class => ['entry', (meet_up.participate?(current_user) ? "participate" : nil)].compact.join(' ') do
          %div
            .left
              = l(meet_up.starts_at, :format => :month_day_time)
            .right
              = t('meet_ups.fields.organizer')
              = meet_up.owner.name
          %div= meet_up.title
          %p
            = meet_up.description

app/views/meet_ups/new.g.html.erb
<h2>新しい夜ゼミを企画</h2>
<%= render :partial => 'form.g', :locals => {:submit_message => "以上の内容で新しい夜の分科会を登録する"} %>

app/views/meet_ups/new.html.haml
= ponzu_frame do
  .settings_bg
    %h1= t('meet_ups.headers.create_new_yoruzemi')
    = render :partial => 'form'

app/views/meet_ups/show.g.html.erb
<h2><%= @meet_up.title %></h2>
<% if @meet_up.participate? current_user %>
  あなたははこの夜ゼミに参加予定です。
  <%= form_for @meet_up, :url => participate_meet_up_path(@meet_up) do |f| %>
    <%= hidden_field_tag :_method, 'put' %>
    <%= f.hidden_field :id %>
    <%= f.submit "参加をキャンセルする" %>
  <% end %>
<% else %>
  <%= form_for @meet_up, :url => participate_meet_up_path(@meet_up) do |f| %>
    <%= hidden_field_tag :_method, 'put' %>
    <%= f.hidden_field :id %>
    <%= f.submit "ここをクリックすると参加できます" %>
  <% end %>
<% end %>
  <div class="controls">
    <%= link_to '[編集する]', edit_meet_up_path(@meet_up) if current_user == @meet_up.owner %> 
  </div>
<div>
<span class="pink">■</span> 開始／集合時刻<br />
<%= @meet_up.starts_at ? @meet_up.starts_at.strftime('%m月%d日 %p %l:%M') : '未定'%>
</div>
<div>
<span class="pink">■</span> 店／集合場所<br />
<%= @meet_up.venue %> &nbsp;&nbsp;<%= !@meet_up.venue_url.blank? ? link_to("[リンク]", @meet_up.venue_url) : 
                         @meet_up.venue_url%>
</div>
<div>
<span class="pink">■</span> 幹事<br />
<%= link_to @meet_up.owner.name, ksp(user_path(@meet_up.owner))%>
</div>
<div>
<span class="pink">■</span> 幹事連絡先<br />
<%= @meet_up.owner_phone %>
</div>

<span class="pink">■</span> 説明<br />
<%= @meet_up.description %><br />
<span class="pink">■</span> 参加予定者<br />
<%= @meet_up.participants.map{|p|
      link_to p.name, p
    }.join(', ').html_safe %><br />
<span class="pink">■</span> コメント<br />
<% @meet_up.meet_up_comments.each do |c| %>
  <div class="comment">
    <%= c.created_at.strftime('%m-%d %p%l:%M') %>&nbsp;&nbsp;
    <%= link_to c.user.name, user_path(c.user), :style => "color:inherit" %><br />
    <%= c.content %>
  </div>
<% end %>
<h3>新しいコメントを追加</h3>
<%= form_for(MeetUpComment.new(:meet_up_id => @meet_up.id)) do |f| %>
  <%= f.hidden_field :meet_up_id %>
  <%= f.text_area :content, :cols => nil, :rows => nil %>
  <%= f.submit "コメントを投稿する"%>
<% end %>
</div>

app/views/meet_ups/show.html.haml
= ponzu_frame :title_args => {:title => "JSDB2013 Yoruzemi: #{@meet_up.title}"} do
  .panel
    = link_to t('meet_ups.buttons.back_to_list', :date_string => @meet_up.starts_at.strftime('%m/%d')), 
              ksp(:meet_ups_path, :date => to_date_string(@meet_up.starts_at)),
              :class => 'button arrowleft icon'
  .panel
    %h1= "#{t('meet_ups.name')}: “#{@meet_up.title}”"
    = link_to t('meet_ups.buttons.edit_button'), ksp(edit_meet_up_path(@meet_up)), :class => "button icon edit" if current_user == @meet_up.owner
    %dl.panel
      %dt= t('meet_ups.fields.starts_at_or_assembly_time')
      %dd= @meet_up.starts_at ? l(@meet_up.starts_at, :format => :month_day_time) : t('meet_ups.undecided')
      %dt= t('meet_ups.fields.restaurant_or_assembly_place')
      %dd
        = @meet_up.venue
        &nbsp;
        = !@meet_up.venue_url.blank? ? link_to(t('meet_ups.fields.link'), @meet_up.venue_url, :class => "button icon arrowright") : @meet_up.venue_url
      %dt= t('meet_ups.fields.organizer')
      %dd= link_to @meet_up.owner.name, ksp(user_path(@meet_up.owner))
      %dt= t('meet_ups.fields.organizer_contact')
      %dd= @meet_up.owner_phone
      %dt= t('meet_ups.fields.people_planning_to_participate')
      %dd= @meet_up.participants.map{|p| link_to p.name, ksp(user_path(p))}.join(', ').html_safe
    %h3= t('meet_ups.fields.description').upcase
    .panel= @meet_up.description
  .panel
    = render :partial => "participate_button"
  .panel
    %h3= t('meet_ups.comments')
    = render :partial => 'meet_up_comments'