config/routes.rb
Rails.application.routes.draw do

  resources :conferences do
    collection do
      get :notifications
      post :delegate
    end
  end

  resources :messages

  match "/manifest" => "dashboard#cache_manifest"
  
  resources :authors do
    member do
      post :replace
    end
  end

  resources :submissions do
    member do
      put :update_institutions
    end
  end
  
  resources :umin_rows

  resources :meet_up_comments

  resources :participations

  resources :meet_ups do
    member do
      put 'participate'
    end
  end

  resources :global_messages
  
  resources :receipts do
    collection do
      put 'mark_read_by_sender'
      put 'mark_read'
      put 'mark_unread'
    end
  end

  resources :likes do
    collection do 
      get 'by_day'
      post 'batch_request_likes'
      post 'vote'
      get 'my_votes'
      get 'likes_report'
      get 'votes_report'
    end
    member do
      get 'my'
      get 'my_schedule'
      put 'schedulize'
      put 'unschedulize'
      put 'secretify'
    end
  end

  get "user_sessions/new"

  get "browser(/:session_id)" => "browser#list", :as => :list_browser

  get "browser/details/:presentation_id" => "browser#details"
  
  get "login" => "user_sessions#new", :as => :login
  get "logout" => "user_sessions#destroy", :as => :logout

  get "schedule" => "schedule#index"

  resources :pages

  resources :authorships do
    collection do
      post 'sort'
      post 'drop_on_submission'
    end
  end

  resources :comments do
    member do
      get 'reply'
    end
  end

  resources :rooms do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  
  resources :poster_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end
    collection do
      get 'container'
    end
  end

  resources :booth_sessions do
    member do
      get 'like_highlights'
      get 'list'
      get 'list_highlights'
      get 'show_test'
    end    
  end
  
  resources :timetable do
    member do
      get 'like_highlights'
      get 'list'
    end
    collection do
      get 'container'
    end
  end
  
  resources :dashboard do
    collection do
      get 'liked_presentations_ajax'
      get 'my_presentations_ajax'
      get 'scheduled_presentations_ajax'
      get 'private_messages_ajax'
      get 'meet_ups_ajax'
      get 'global_messages_ajax'
      get 'notifications'
      get 'global_messages'
      get 'my_presentations'
      get 'my_meet_ups'
      get 'private_messages'
      get 'social_links'
      post 'batch_request_pages'
    end
  end
  
  resources :sessions do
    member do
      get 'detail'
      get 'poster_row'
      get 'social_box'
      get 'poster_social_box'
      get 'download_pdf'
      get 'download_full_day_pdf'
      put 'order_presentations_by_number'
      put 'set_presentation_duration'
      get 'query'
      put 'change_children_presentation_types'
    end
    collection do
      post 'batch_request_liked_sessions'
      get 'download_full_pdf'
      get 'download_pdf_by_name'
    end
  end

  resources :presentations do
    member do
      get 'next'
      get 'previous'
      get 'likes'
      get 'comments'
      get 'social_box'
      put 'toggle_schedule'
      post 'create_comment'
      get 'related'
      get 'heading'
      put 'change_ad_category'
    end
    collection do
      get 'my'
      post 'sort'
      post 'batch_request_likes'
    end
  end

  resources :users do
    member do
      put 'set_global_message_to_read'
      put 'reset_read_global_messages'
      get 'settings', :to => 'users#settings'
      put 'settings', :to => 'users#update_settings'
      get 'edit_name'
      put 'update_name'
      get 'admin_panel'
      put 'assign_author'
    end
    collection do
      get 'admin_search'
      get 'admin_search_by_registration_id'
    end
  end
  
  resources :user_sessions do
    collection do
      post 'switch'
    end
  end
  
  resources :private_messages do
    collection do
      get 'threads'
    end
  end

  match 'private_messages/conversation/:with' => 'private_messages#conversation', :as => 'conversation_private_messages'

  resources :search

  match 'docs/batch' => 'docs#batch', :as => "docs_batch"
  match 'docs/test_batch' => 'docs#test_batch', :as => "docs_test_batch"
  match 'docs(/:folder)/manifest' => 'docs#manifest', :as => "docs_manifest"
  match 'docs/:page(/:sub_page)' => 'docs#show', :as => "docs", :via => [:get]
  match 'docs/:page(/:sub_page)' => 'docs#create', :as => "docs", :via => [:post]
  match 'docs(/)' => 'docs#index', :as => "docs_root"

  match 'tests/:page(/:sub_page)' => 'tests#show', :as => "tests", :via => [:get]

  match 'admin/:action' => 'admin', :as => "admin"

  match ':page' => 'static#show', :as => :static, 
        :constraints => {:page => /ponzu_frame|ponzu_admin_frame|rake_reports/}

  match 'system/ks_cache_version' => "conferences#ks_cache_version", :as => :ks_cache_version

  root :to => 'static#layout'

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  # We used to use this controller for tests so we have
  # a "docs" layout. We don't use it here so we change it.
  layout "application"
  # This allows us to use docs_controller for full HTML responses (not XHR)
  before_filter :ignore_default_kamishibai_hash_tag
  set_kamishibai_expiry [:show] => 24 * 60 * 60
  @@action_sanitize_regex = /[^0-9a-zA-Z_-]/

  # TODO: Think about doing this to make it easy to render markdown
  # http://stackoverflow.com/questions/4163560/how-can-i-automatically-render-partials-using-markdown-in-rails-3/4418389#4418389
  def show
    action = action_string
  	respond_to do |format|
  		format.html{
        if request.xhr?
          render :action => action, :layout => false
        else
          if galapagos?
            render :action => action, :layout => "layouts/galapagos"
          else
            render :action => action
          end
        end
      }
    end
  end

  # for testing post reqeusts
  def create
    action = action_string
    respond_to do |format|
      format.html{
        if request.xhr?
          render :action => action, :layout => false
        else
          render :action => action
        end
      }
    end
  end

  def index
  end

  # Since we contain user specific information in the top page, and we 
  # need to cache that page, we have to think about how we handle login
  # and logouts with the cache_manifest.
  # Refer to the Numbers file cachemanifest_scheme.numbers
  def manifest
    action = [params[:folder], "manifest"].join("/")
    headers['Cache-Control'] = "max-age=0, no-cache, no-store, must-revalidate"
    headers['Pragma'] = "no-cache"
    headers['Expires'] = "Wed, 11 Jan 1984 05:00:00 GMT"
    headers['Content-Type'] = "text/cache-manifest"
    render :action => action, :layout => false
  end


  def batch
    responses = {}
    pages = ["mockup", "mockup2", "ponzu", "showcase", "tests"]

    pages.each do |page|
      path = File.expand_path("#{page}", "#{__FILE__}/../../views/docs/");
      all_html_files = Dir.entries(path).delete_if{|e| e !~ /\.html\./}.map{|e| e.sub(/\.html\..*$/, "")}

      all_html_files.each do |sub_page|
        url = docs_path("#{page}/#{sub_page}")
        body = run_action(:show, {page: page, sub_page: sub_page}, {xhr: true})
        responses[url] = body
      end
    end
    render :json => responses
  end

  # Test to load a huge number of pages
  # Test results:
  # After the JSON response has been received, loading up the
  # database returns immediately because database actions are asynchronous.
  # However, database queries have simply queued up meaning that subsequent
  # requests to the database (and hence all page transitions) simply wait.
  # One way is to make sure that we don't wait on the database while doing
  # page transitions (but the issue is that we want to know the cache) state
  # in order to set timeout.
  # A Load button makes a lot of sense but it has to work with the asynchronous interface.
  def test_batch
    responses = {}
    page = "showcase"
    sub_page = "introduction"
    1.upto(1000) do |i|
      url = docs_path("#{page}/#{sub_page}")
      body = run_action(:show, {page: page, sub_page: sub_page}, {xhr: true})
      responses["#{url}_#{i}"] = body      
    end
    render :json => responses
  end

  private

  def action_string
    [params[:page], params[:sub_page]].map{|s| s.gsub(@@action_sanitize_regex, '_')}.join('/')
  end

end

app/views/docs/showcase/application_cache.html.haml
= ks_element :id => "application_cache",
             :data => { :title => "Application Cache",
                       :container => "ipadish_content",
                       :"container-ajax" => docs_path(:page => "showcase/layout") } do
  .panel
    :markdown
      # Application Cache

      Correct use of the application cache is critical to using Kamishibai offline.
      The [Appcache Facts](http://appcachefacts.info) website is a great resource for this.

      [A List Apart](http://alistapart.com/article/application-cache-is-a-douchebag) also is 
      great and has information about how to create an offline app with the combination
      of localStorage and AppCache, without our hash-URL scheme. Unfortunately, relying on
      the AppCache `FALLBACK` has its drawbacks. The biggest issue in our context is
      "The experience on a temperamental connection isn’t great". A temperamental connection
      is exactly what we get at conferences. Instead of relying on `FALLBACK`, we would like
      the flexibility to define our own timeouts for fallback situations.

      ## What to and what not to cache

      The application cache is not good for stuff that will change frequently. You
      cannot invalidate a single entry in Appcache. To invalidate the cache, you modify the
      manifest file, which will cause the browser to re-request every single entry and 
      update the cache in its entirety. Although the re-requests will honor browser cache
      settings (standard If-Modified-Since headers) and will not download files that have not
      changed, the fact remains that a large number of requests will be made.

      Therefore, we only cache static stuff. This is mostly Javascript, CSS and image files.

      We will however cache the bootloader page (the root page). To do this, instead of putting
      the bootloader URL in the cache manifest (which isn't necessary because Appcache will cache
      the current page if it points to a manifest file), we simply make sure that the bootloader
      page and the bootloader page only will point to a manifest file. 

      This should go into the `CACHE` section.

      Don't put anything in the AppCache that has any state information. Only put things that can be
      uniquely identified by URL.

      In the `NETWORK` section, we should have `*`, `http://*` and `https://*`

      In the `FALLBACK` section, we could solve situations where the user tries to
      access a non-hash type URL when offline. The fallback page would redirect to a hash-type
      URL which is likely to be handled with offline cache.

      ## The bootloader should be very minimal

      Specifically, the bootloader should not contain any state information including login status,
      language status, etc. This makes working with Appcache complicating.

app/views/docs/showcase/base_css.html.haml
= ks_element :id => "base_css",
             :data => { :title => "Base CSS",
                       :container => "ipadish_content",
                       :"container-ajax" => docs_path(:page => "showcase/layout") } do
  .panel
    :markdown
      # Base CSS

      Kamishibai does not impose pre-designed widgets on the developer. The developer
      is free to use any design that they wish to reflect the brand image they
      want to express. This is very different from jQuery Mobile, Sencha Touch, etc.
      These frameworks focus on providing a native-like experience, and make it
      difficult to customize the look-and-feel, other than changing colors.

      That said, there are several widgets that are of wide utility, like lists and
      buttons. We provide a simple set of these, which can easily be overridded in 
      a CSS file. The purpose of these pre-made widgets is to unify the HTML so
      that CSS can easily be applied. What we will provide is the base CSS and a 
      set of examples to show how they should be used in the basic widgets.

      We will use the same base CSS for both PCs and smartphones.

      ## Font size

      1. Button labels and list labels should have a default
         font size of 20px.
      2. Font size for reading lots of text should be 16px.
      3. Supplementary fonts can be 14px or 10px.

      ## Font family

      We use simple helvetica, arial, sans-serif. For Windows, we might use merio.

      ## Headers

      Headers are where a lot of the branding takes place so we don't impose any rules
      on it. 

      The only restriction is that buttons should be at least 44px x 44px in size.

      ## Panels

      iOS uses panels when there is more than one kind of information is on a single
      page. Panels are often accompanied by titles.

      1. CSS class "panel_title"
      2. CSS class "panel"

      ## Lists

      iOS has two types of lists. One covers the whole screen and leaves nothing on the side.
      There might be a search window on the header.

      The other type is a list inside a panel.

      Apple always puts an arrow to the right of a list item to indicate that you can click this
      button. Others like Twitter don't bother and assume that they user knows that you can
      click it.

      We will provide simple CSS of both types of list with arrows.

      ## Buttons

      iOS has two kinds of button. The kind that you embed in menus and the kind that are shown
      in dialog boxed. The former is quite small. The latter, quite large.

app/views/docs/showcase/composition_test.html.haml
= ks_element :id => "composition_test",
             :data => { :title => "Fragment composition",
                       :container => "ipadish_content",
                       :"container-ajax" => docs_path(:page => "showcase/layout") } do
  .panel
    :markdown
      # Kamishibai compositor tests

      ## Loading a fragment with `ks_ajax_placeholder`

      The following element was loaded with `ks_ajax_placeholder` from
      `"docs/showcase/composition_ajax"`
    = ks_ajax_placeholder :id => "ajax_placeholder_test",
                          :data => {:ajax => docs_path("showcase/composition_ajax")}

    :markdown
      The following element was a `ks_placeholder` and was populated from
      `"docs/showcase/composition_ajax"` when the previous `ks_ajax_placeholder`
      received its response.
    = ks_placeholder :id => "placeholder_test"

    :markdown
      The following element originally did not have a background color, but 
      `"docs/showcase/composition_ajax"` contained `ks_modify_elements` to
      set the class `highlight` so it now should be be a highlight color.
    #should_turn_yellow
      This element didn't have a class but 
      %code "docs/showcase/composition_ajax"
      modified it so that it should have a highlight background color now.

    :markdown
      The following element did not have any inline style, but 
      `"docs/showcase/composition_ajax"` contained a `script` tag
      with JavaScript to set the style to `"background-color:orange"`
      so it should now be orange.
    #should_turn_orange
      This element originally had no inline style but 
      %code "docs/showcase/composition_ajax"
      modified it through the following Javascript in a `script` tag 
      so it should now be orange.
      %pre
        %code
          :preserve
            (function() {
              var e = document.getElementById('should_turn_orange');
              e.style.backgroundColor = 'orange';
            })();

app/views/docs/showcase/fragments.html.erb
<%= ks_element :id => "fragments",
            :data => {
              :title => "Fragments",
              :container => "ipadish_content",
              :"container-ajax" => docs_path(:page => "showcase/layout")
            } do %>
  <div class="panel">
    <%= markdown_render <<MARKDOWN

# Why Fragments?

Kamishibai breaks pages down into fragments. Below are the reasons
why we do it.

## You can reuse fragments between mobile and desktop

Contrary to our expectations, when we created both the desktop and
smartphone versions of the MBSJ2012 website, we converged a lot
on the controllers and views. This is due to the fact that we
wanted a consistent look-and-feel, and that for the desktop site,
we actually targetted the iPad with a 728px native horizontal resolution
which is much less than current day websites are designed for.

If we extend support for fragments and use a suitable URL scheme 
(described elsewhere), we envision that we can actually use the 
same identical controller and views for both desktop and smartphone
versions.

## Fragments make cache management easier

Regular HTML pages contain a lot of stuff. This means that when something
gets uploaded on the website, there are potentially multiple HTML pages
that have to be expired. If we use fragments, this expiry is much easier.

First, since a fragment will depend on only a small number of data, the
number of fragments to expire will be smaller compared to whole pages.

Additionally, if we are using time-based expiration, then we can set
different page elements to expire at a different time. For example, 
the top navigation elements will seldom change so we can set a longer
expiry time for these.



MARKDOWN
%>
  </div>
<% end %>

app/views/docs/showcase/general_structure.html.erb
<%= ks_element :id => "general_structure",
               :data => {
               	 :title => "Kamishibai General Structure",
               	 :container => "ipadish_content",
                 :"container-ajax" => docs_path(:page => "showcase/layout")
               } do %>
  <div class="panel">
  	<h1>General Structure of Kamishibai</h1>
  	<p>
  		Kamishibai is not a general purpose framework but a one that expects that
  		you want to create a multilingual application that works on multiple
  		devices. Hence Kamishibai imposes a structure that enables this.
  	</p>
  	<h2>Load sequence</h2>
    <h3>First load</h3>
  	<p>
  		Kamishibai breaks up a single HTML document into multiple requests. The simplest
  		Kamishibai page will make two HTML requests to the server, one to load the
  		base page, and the other to load the contents. If the page contains sub-page 
  		fragments, then requests will be made for each fragment.
  	</p>
  	<p>
  		Whereas this looks inefficient since the number of requests increase, this is not
  		necessarily the case. If we use HTML5 Application cache, then we can put 
  		some of these fragments into the cache so that we don't send requests to the
  		Internet. We describe how this looks like below.
  	</p>
  	<h4>The first load is for the headers and application containers</h4>
  	<p>
  		The first request is for an empty page that contains headers loading CSS &amp; Javascript. This request corresponds to the path portion of the URL. It will
  		typically be device dependent, but not locale dependent.
  	</p>
  	<p>
  		Since this page will typically be completely static, it is safe to place this in 
  		the Application cache. Even if it is not in the Application cache, the server
  		should be able to render it very quickly. In either case, this request should
  		be very quick in most cases, and may be completely local.
  	</p>
  	<h4>The first load triggers loading of CSS, Javascript and HTML fragments</h4>
  	<p>
  		The first load contains the header and minimal DOM structure. Since the first load, if
      cached in the application cache, will load almost immediately, this means that the 
      request for javascript files and CSS will start very early compared to regular web pages.
      Regular web pages load all the HTML in one request, and unless that page is cached on
      the server, it may take several hundred milliseconds or even seconds to load.
  	</p>
    <p>
      For example, if we look at asahi.com, the first page request has a latency of 144ms and
      the data transfer takes 194ms. Since a significant amount of data has to be transferred
      before the browser can request any of the resources in the header, the first CSS request 
      fires roughly 300ms after the initial request.
    </p>
    <p>
      On the other hand, if we load a Kamishibai page (with application cache but no other cache),
      then the first load will be very fast (latency 0.3ms, transfer 22.9ms). CSS and JS will load
      starting at about 20ms. The Ajax request to load the actual contents of the page fires at about
      50ms since the request, after JS has been loaded and rendered. Therefore, even though
      there is a penalty associated with a double request, if the first request is simple, static
      and cached, then the penalty will not be more than a few tens of milliseconds. Depending on the
      cache state, it is possible to imagine situations where a double request might even actually
      be faster (i.e. if the CSS takes a long time to load).
    </p>
  </div>
<% end %>

app/views/docs/showcase/layout.html.haml
= ks_hidden_page(:id => "showcase", 
                   :class => %w(program fluid_multicolumn), 
                   :data => { :title => "Showcase" }) do
  %div
    = render :partial => 'header'
    #ipadish.body
      = ks_ajax_placeholder :id => "ipadish_left",
                            :class => "left_column",
                            :data => { :ajax => docs_path(:page => "showcase/left_navigation")}
      #ipadish_content.two_column_content
      %div{style: "clear:both"}

app/views/docs/showcase/left_navigation.html.haml
= ks_element :id => "ipadish_left" do
  %ul
    %li= link_to "ToDos", ksp(:docs_path, 'showcase/todos')
    %li= link_to "Data management", ksp(:docs_path, 'showcase/data_management')
    %li= link_to "Introduction", ksp(:docs_path, 'showcase/introduction')
    %li= link_to "Key benefits of Kamishibai", ksp(:docs_path, 'showcase/key_benefits')
    %li= link_to "Purpose of this showcase", ksp(:docs_path, 'showcase/purpose_of_showcase')
    %li= link_to "How to write Kamishibai pages", ksp(:docs_path, 'showcase/writing_pages')
    %li= link_to "General structure", ksp(:docs_path, 'showcase/general_structure')
    %li= link_to "Benefits of compositor architecture", ksp(:docs_path, 'showcase/compositor_architecture')
    %li= link_to "URL scheme", ksp(:docs_path, 'showcase/url_scheme')
    %li= link_to "Fragments", ksp(:docs_path, 'showcase/fragments')
    %li= link_to "Fragment composition", ksp(:docs_path, 'showcase/composition')
    %li= link_to "Fragment composition test", ksp(:docs_path, 'showcase/composition_test')
    %li= link_to "Form Handling", ksp(:docs_path, 'showcase/forms')
    %li= link_to "Javascript Templating", ksp(:docs_path, 'showcase/templating')
    %li= link_to "Separating Static content", ksp(:docs_path, 'showcase/separating_static')
    %li= link_to "Extreme DRY views", ksp(:docs_path, 'showcase/dry_views')    
    %li= link_to "Network Situation", ksp(:docs_path, 'showcase/network_situation')
    %li= link_to "Offline Viewing", ksp(:docs_path, 'showcase/offline_viewing')
    %li= link_to "Application Cache", ksp(:docs_path, 'showcase/application_cache')
    %li= link_to "iPad-first design", ksp(:docs_path, 'showcase/ipad_first')
    %li= link_to "iMode", ksp(:docs_path, 'showcase/imode')
    %li= link_to "Base CSS", ksp(:docs_path, 'showcase/base_css')
    %li= link_to "Widgets", ksp(:docs_path, 'showcase/widgets')
    %li= link_to "Rails & Kamishibai", ksp(:docs_path, 'showcase/rails_and_kamishibai')
    %li= link_to "Kamishibai & Turbolinks", ksp(:docs_path, 'showcase/kamishibai_and_turbolinks')
    %li= link_to "Ponzu Concept", ksp(:docs_path, 'ponzu/concept')
    %li= link_to "Ponzu Author UI", ksp(:docs_path, 'ponzu/author_ui')
    %li= link_to "Ponzu Admin UI", ksp(:docs_path, 'ponzu/admin_ui')
    %li= link_to "Ponzu Schema", ksp(:docs_path, 'ponzu/schema')
    %li= link_to "Ponzu jQuery", ksp(:docs_path, 'ponzu/jquery')
    %li= link_to "Ponzu Exhibitors", ksp(:docs_path, 'ponzu/exhibitors')
    %li= link_to "Kamishibai tests (not working)", ksp(:docs_path, 'ks_tests')
    %li= link_to "Homepage ideas", ksp(:docs_path, 'homepage/introduction')
    %li= link_to "Mockup", ksp(:docs_path, 'mockup/dashboard')
    %li= link_to "Mockup2", ksp(:docs_path, 'mockup2/dashboard')
    %li= link_to "Test forms", ksp(:docs_path, 'tests/forms')
    %li= link_to "Recursive load test", ksp(:docs_path, 'tests/recursive_load_test')
    %li= link_to "Unit tests", tests_path(:page => "unit_test")

app/views/docs/showcase/offline_viewing.html.erb
<%= ks_element  :id => "offline_viewing",
                :data => {
                  :container => "ipadish_content",
                  :"container-ajax" => docs_path(:page => "showcase/layout"),
                  :title => "Offline Viewing"
                } do %>
  <div class="panel">
    <%= markdown_render <<MARKDOWN

# Offline viewing

Offline viewing in Kamishibai is not a simple caching mechanism that replicates what
native apps generally do (download the whole shit). Instead, Kamishibai aims to
combine the benefits of the web with offline capability. What we want to provide
is a seamless experience where you can view the content instantly if you are online,
and backup data is automatically downloaded in the background. We want to make
it so that the user never has to conciously realize that they are syncing data.

## The problem with other offline apps

Most offline capable apps like the one for Asahi shinbun or even the Financial Timeweb application load content at the beginning. The user is forced to wait until the data is downloaded; until
downloading is finished, the user cannot enter a word. We think that this is really crummy.

For example, if an attendee wanted to quickly look up what's going on in the next room,
he would still be forced to wait until all the other stuff syncs. If the WiFi is slow,
than this could take ages.

The solution is to not be obsessed with providing up-to-date data, but instead to show 
what you've got as soon as you can.

The other kind of offline app is the one that you have to manually sync. Users are
expected to know when their data is stale, and then they are supposed to navigate to
and click a sync button. The sync will also take a few minutes, during which the user
cannot use his device. This is also very crummy.

## Our solution

There are two tenets to our solution.

First is that the user should get access to whatever data they have as soon as possible.
The second is that the user should not have to worry about syncing (the initial data
load might be too much for background syncing so we'll have a button for that).

Regarding the first tenet, the device should first check to see if it can rely on
the cached version by looking at the expiry time. If it has expired, then it 
attempts to download the most up-to-date version from the server within a reasonable 
amount of time. If it can not, then it will fallback to the version in the cache.
The idea is that a stale version is better than a long wait. My experience is that
5 seconds is what users will wait for most of the time, so we will fallback to the
cached version if we cannot get it from the server within that amount of time.

Basically, we ensure that the user has to wait only 5 seconds.

The second tenet can be solved by syncing in the background. This should work if the number
of updates is not too large. However, if there are lots of updates, then this will create
a long queue on WebSQL and prevent page transitions. Currently, I don't know how to work
around this. For the first load, we probably need a button.

## Our batch upload solution

After testing UI responsiveness during the updating of thousands of DB records, we
conclude that a **Download** button is necessary, and that we will have to block the UI
during this. 

However, we can still maintain user friendliness.

1. The user has to explicitly press the **Download** button to download to local. Unlike 
   many newspaper apps, you don't have to download if you don't want to. The
   user can interact with the website *online*, even if the data has not been downloaded.
   They don't have to wait until the data downloads. This means very little wait time;
   just need to wait as long as a regular website.
2. The user should push the **Download** button when they are online with a reliable WiFi
   connection.
3. If the user want's to abort, a simple **reload** is sufficient. We might provide a button for
   this.
4. After the first **Download**, subsequent updates should not require that much data and should
   be pretty quick. We could do these in the background, without the user even noticing.
5. If we do need to **Download** a lot of data, we should show a notification on the screen.
6. We need to manage database versions. The best way is to use a timestamp.
7. For example, for batch downloading `Presentation` pages. The version will be equal to the 
   most recently updated `Presentation` object's timestamp. When a request to batch download
   `Presentations` is sent from the browser, it will also send the last downloaded version number.
   Since the version number is a simple timestamp, it is trivial to query the `Presentations`
   that were updated since the last request. We can also cache the response in memecached with
   a key for "[last_downloaded_version]-[most_recently_updated_presentation_timestamp]".
8. We should have an action that returns a JSON has of each `version` for each batch download.
   We will have batch download actions for `Presentations`, `Authors`, `Sessions`, etc.

## Batch retrieval of pages for offline storage

We provide a `batch` action on controllers. These actions will return a JSON response
with multiple pages in a hash with the request URLs as keys.

## Offline storage databases

WebSQL is available on Safari and Android Browser. Chrome has a severe storage limit of WebSQL,
so it's probably better to use IndexedDB. Firefox will have to use IndexedDB. IE <= 9 doesn't
support either. We will have to use localStorage for this.

Depending on the size of the database, localStorage might be sufficient to hold everything. If
this is the case, we might fallback to localStorage. Otherwise, localStorage should be only as
a temporary memcached-like store. In this case, batch uploading tends to be complicated because
we need to provide a customized version for each user and we have to make sure that we don't exceeed localStorage limits.

The goal is to completely remove the need to flush the cache. Then things should be simpler.

## Future directions

1. Make it possible to like presentations offline. We need a `Model` for this.
2. Make it possible to take notes offline. We need a `Model` for this.

## Some cautions

1. To make incremental updates easier, we should never totally delete a page. Instead, we should blank it out. Otherwise, if we had an auditing system on Rails, we might be able to keep track of deletions.

MARKDOWN
%>
  </div>
<% end %>